DROP TABLE MealPlanDB;
DROP TABLE WorkoutPlanDB;
DROP TABLE FitnessGoalDB;
DROP TABLE BMILogDB;
DROP TABLE MealLogDB;
DROP TABLE ExerciseLogDB;
DROP TABLE WorkoutLogDB;
DROP TABLE UserDB;
DROP TABLE ExampleExerciseDB;
DROP TABLE ExampleWorkoutDB;	
DROP TABLE MealDB;



